version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip install -r requirements.txt --target package
      - pip install pytest pytest-cov
  post_build:
    commands:
      - zip -r deploy_pack.zip app package requirements.txt --exclude *__pycache__*
artifacts:
  type: zip
  files:
    - deploy_pack.zip
