version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip install -r requirements.txt --target package
      - pip install pytest pytest-cov
artifacts:
  type: zip
  files:
    - app
    - package
    - requirements.txt
