version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
artifacts:
  type: S3
  name: "aws_sam_practice.zip"
  files:
    - app/**/*
